class FlowLocalizations {
  static const Map<String, Map<String, String>> values = {
    'az': {
      'dashboardSubtitle': 'Təhlilə haradan başlayaq?',
      'oldPoint': 'Köhnə nöqtəni\ninkişaf etdirmək',
      'oldPointSubtitle': 'Mövcud biznes üçün audit',
      'newPoint': 'Yeni nöqtə\ntapmaq',
      'newPointSubtitle': 'Yeni zona və məkan seçimi',
      'dashboardFooter':
          'Pulsuz minimum audit • Xəritədə zona analizi • AI assistent',
      'oldPointHeader': 'Köhnə nöqtəni inkişaf etdir',
      'businessSection': '1. Biznes sahəsi',
      'businessSectionSubtitle': 'Bir və ya bir neçə sahə seçin',
      'problemSection': '2. Əsas problem',
      'problemSectionSubtitle': 'Maksimum iki variant seçə bilərsiniz',
      'addressSection': '3. Ünvan',
      'addressSectionSubtitle': 'Nöqtənin ünvanını daxil edin',
      'addressHint': 'Şəhər, küçə və ya ünvan',
      'otherSector': 'Başqa sfera...',
      'otherBusiness': 'Başqa biznes...',
      'otherProblem': 'Digər problem...',
      'close': 'Bağla',
      'auditStart': 'AUDİTƏ BAŞLA →',
      'auditLoading': 'Audit hazırlanır...',
      'freeAuditNote':
          'Pulsuz versiya minimum hesabat və əsas zona göstəricilərini əhatə edir.',
      'auditFailed': 'Audit baş tutmadı',
      'reportTitle': 'Minimum hesabat',
      'auditReady': 'Audit hazırdır',
      'score': 'Keçid balı',
      'traffic': 'Piyada trafiki',
      'competitors': 'Rəqiblər',
      'parking': 'Parking',
      'stops': 'Dayanacaq',
      'reviews': 'Rəy',
      'comments': 'Şərhlər',
      'trafficUnavailable': 'Məlumat yoxdur',
      'hoursAvailable': 'İş qrafiki var',
      'reportDescription':
          'Daha ətraflı baxış üçün nəticəni xəritədə açın. Rəqibləri, nöqtələri və keçid balını vizual müqayisə edin.',
      'viewMap': 'XƏRİTƏDƏ BAX',
      'fullReport': 'Tam hesabatı aç',
      'paidUpgrade':
          'Ödənişli versiyada rəqib xəritəsi, tam hesabat və tövsiyələr açılır.',
      'assistantTitle': 'AI Assistent',
      'assistantSubtitle': 'Yeni nöqtə seçimi',
      'chatHint': 'Mesajınızı yazın...',
      'autocompleteHint': 'İlk 3 hərfi yazın...',
      'assistantWelcome':
          'Salam! Biznesiniz üçün ideal məkanı tapmağa kömək edəcəyəm. Artıq nəzərdə tutduğunuz obyekt var, yoxsa ən yaxşı ərazini sıfırdan seçməyimi istəyirsiniz?',
      'startNew': 'Sıfırdan axtarmaq',
      'ownAddress': 'Öz ünvanım var',
      'chooseBusiness': 'Əla. Hansı biznes sahəsi üçün zona axtarırsınız?',
      'writeAddress':
          'Ünvanı yazın. Sonra həmin nöqtənin ətrafını və rəqibləri xəritədə göstərəcəyəm.',
      'writeArea': 'İndi şəhər və ya axtarılacaq ərazini yazın.',
      'writeCustomBusiness': 'Biznes sahəsini yazın.',
      'writeAddressOrCity': 'Ünvanı və ya şəhəri yazın.',
      'selectBusiness': 'Bu nöqtə üçün biznes sahəsini seçin.',
      'analysisReady':
          'Canlı 2GIS analizi hazırdır. Zonalara xəritədə baxa və rəqibləri müqayisə edə bilərsiniz.',
      'mapZones': 'ZONALARA XƏRİTƏDƏ BAX',
      'analysisFailed': '2GIS analizi alınmadı',
      'business_cafe': 'Kafe',
      'business_restaurant': 'Restoran',
      'business_retail': 'Məhsullar / Pərakəndə',
      'business_beauty': 'Gözəllik',
      'business_health': 'Təbabət',
      'business_auto': 'Avtoservis',
      'business_hotel_guesthouse': 'Otel / Qonaq evi',
      'business_education': 'Təhsil',
      'problem_traffic': 'Piyada trafiki aşağı düşüb',
      'problem_competitors': 'Rəqiblər açılıb',
      'problem_ticket': 'Orta çeki qaldırmaq istəyirəm',
      'problem_customers': 'Müştəri axını azdır',
      'problem_visibility': 'Görünürlük zəifdir',
      'free': 'Pulsuz',
    },
    'en': {
      'dashboardSubtitle': 'Where should we start the analysis?',
      'oldPoint': 'Improve an\nexisting location',
      'oldPointSubtitle': 'Audit for an existing business',
      'newPoint': 'Find a new\nlocation',
      'newPointSubtitle': 'Choose a new area and location',
      'dashboardFooter':
          'Free minimum audit • Zone analysis on map • AI assistant',
      'oldPointHeader': 'Improve existing location',
      'businessSection': '1. Business sector',
      'businessSectionSubtitle': 'Select one or more sectors',
      'problemSection': '2. Main problem',
      'problemSectionSubtitle': 'You can select up to two options',
      'addressSection': '3. Address',
      'addressSectionSubtitle': 'Enter the location address',
      'addressHint': 'City, street or address',
      'otherSector': 'Other sector...',
      'otherBusiness': 'Other business...',
      'otherProblem': 'Other problem...',
      'close': 'Close',
      'auditStart': 'START AUDIT →',
      'auditLoading': 'Preparing audit...',
      'freeAuditNote':
          'The free version includes a minimum report and key zone metrics.',
      'auditFailed': 'Audit failed',
      'reportTitle': 'Minimum report',
      'auditReady': 'Audit is ready',
      'score': 'Passage score',
      'traffic': 'Pedestrian traffic',
      'competitors': 'Competitors',
      'parking': 'Parking',
      'stops': 'Stops',
      'reviews': 'Reviews',
      'comments': 'Comments',
      'trafficUnavailable': 'Unavailable',
      'hoursAvailable': 'Hours available',
      'reportDescription':
          'Open the result on the map for more detail. Compare competitors, locations and the passage score visually.',
      'viewMap': 'VIEW ON MAP',
      'fullReport': 'Open full report',
      'paidUpgrade':
          'The paid version unlocks competitor maps, the full report and recommendations.',
      'assistantTitle': 'AI Assistant',
      'assistantSubtitle': 'New location selection',
      'chatHint': 'Write your message...',
      'autocompleteHint': 'Type the first 3 letters...',
      'assistantWelcome':
          'Hello! I will help you find the ideal location for your business. Do you already have a place in mind, or should I choose the best area from scratch?',
      'startNew': 'Search from scratch',
      'ownAddress': 'I have my own address',
      'chooseBusiness': 'Great. Which business sector are you looking for?',
      'writeAddress':
          'Enter the address. I will then show the area and competitors on the map.',
      'writeArea': 'Now enter the city or area to search.',
      'writeCustomBusiness': 'Enter your business type.',
      'writeAddressOrCity': 'Enter an address or city.',
      'selectBusiness': 'Select a business sector for this location.',
      'analysisReady':
          'Live 2GIS analysis is ready. View the zones on the map and compare competitors.',
      'mapZones': 'VIEW ZONES ON MAP',
      'analysisFailed': '2GIS analysis failed',
      'business_cafe': 'Cafe',
      'business_restaurant': 'Restaurant',
      'business_retail': 'Products / Retail',
      'business_beauty': 'Beauty',
      'business_health': 'Healthcare',
      'business_auto': 'Auto service',
      'business_hotel_guesthouse': 'Hotel / Guest house',
      'business_education': 'Education',
      'problem_traffic': 'Pedestrian traffic has decreased',
      'problem_competitors': 'New competitors appeared',
      'problem_ticket': 'I want to increase the average ticket',
      'problem_customers': 'Customer flow is low',
      'problem_visibility': 'Visibility is weak',
      'free': 'Free',
    },
    'ru': {
      'dashboardSubtitle': 'С чего начнём анализ?',
      'oldPoint': 'Развить\nстарую точку',
      'oldPointSubtitle': 'Аудит существующего бизнеса',
      'newPoint': 'Найти новую\nточку',
      'newPointSubtitle': 'Выбор новой зоны и места',
      'dashboardFooter':
          'Бесплатный минимальный аудит • Анализ зоны на карте • AI-ассистент',
      'oldPointHeader': 'Развить старую точку',
      'businessSection': '1. Сфера бизнеса',
      'businessSectionSubtitle': 'Выберите одну или несколько сфер',
      'problemSection': '2. Основная проблема',
      'problemSectionSubtitle': 'Можно выбрать максимум два варианта',
      'addressSection': '3. Адрес',
      'addressSectionSubtitle': 'Введите адрес точки',
      'addressHint': 'Город, улица или адрес',
      'otherSector': 'Другая сфера...',
      'otherBusiness': 'Другой бизнес...',
      'otherProblem': 'Другая проблема...',
      'close': 'Закрыть',
      'auditStart': 'НАЧАТЬ АУДИТ →',
      'auditLoading': 'Аудит готовится...',
      'freeAuditNote':
          'Бесплатная версия включает минимальный отчёт и основные показатели зоны.',
      'auditFailed': 'Аудит не выполнен',
      'reportTitle': 'Минимальный отчёт',
      'auditReady': 'Аудит готов',
      'score': 'Балл проходимости',
      'traffic': 'Пешеходный трафик',
      'competitors': 'Конкуренты',
      'parking': 'Парковка',
      'stops': 'Остановка',
      'reviews': 'Отзывы',
      'trafficUnavailable': 'Нет данных',
      'hoursAvailable': 'Есть график',
      'reportDescription':
          'Откройте результат на карте для подробного просмотра. Сравните конкурентов, точки и балл проходимости.',
      'viewMap': 'СМОТРЕТЬ НА КАРТЕ',
      'fullReport': 'Открыть полный отчёт',
      'paidUpgrade':
          'Платная версия открывает карту конкурентов, полный отчёт и рекомендации.',
      'assistantTitle': 'AI-ассистент',
      'assistantSubtitle': 'Выбор новой точки',
      'chatHint': 'Напишите сообщение...',
      'autocompleteHint': 'Введите первые 3 буквы...',
      'assistantWelcome':
          'Приветствую! Я помогу найти идеальное место для вашего бизнеса. У вас уже есть помещение на примете, или мне подобрать лучший район с нуля?',
      'startNew': 'Искать с нуля',
      'ownAddress': 'У меня есть адрес',
      'chooseBusiness': 'Отлично. Для какой сферы бизнеса ищем зону?',
      'writeAddress':
          'Введите адрес. Затем я покажу окружение точки и конкурентов на карте.',
      'writeArea': 'Теперь введите город или район для поиска.',
      'writeCustomBusiness': 'Введите вид бизнеса.',
      'writeAddressOrCity': 'Введите адрес или город.',
      'selectBusiness': 'Выберите сферу бизнеса для этой точки.',
      'analysisReady':
          'Живой анализ 2GIS готов. Посмотрите зоны на карте и сравните конкурентов.',
      'mapZones': 'СМОТРЕТЬ ЗОНЫ НА КАРТЕ',
      'analysisFailed': 'Не удалось выполнить анализ 2GIS',
      'business_cafe': 'Кафе',
      'business_restaurant': 'Ресторан',
      'business_retail': 'Продукты / Розница',
      'business_beauty': 'Красота',
      'business_health': 'Медицина',
      'business_auto': 'Автосервис',
      'business_hotel_guesthouse': 'Гостиница / Отель',
      'business_education': 'Образование',
      'problem_traffic': 'Пешеходный трафик снизился',
      'problem_competitors': 'Появились конкуренты',
      'problem_ticket': 'Хочу повысить средний чек',
      'problem_customers': 'Низкий поток клиентов',
      'problem_visibility': 'Слабая видимость',
      'free': 'Бесплатно',
    },
    'kk': {
      'dashboardSubtitle': 'Талдауды неден бастаймыз?',
      'oldPoint': 'Ескі нүктені\nдамыту',
      'oldPointSubtitle': 'Қолданыстағы бизнес аудиті',
      'newPoint': 'Жаңа нүкте\nтабу',
      'newPointSubtitle': 'Жаңа аймақ пен орын таңдау',
      'dashboardFooter':
          'Тегін бастапқы аудит • Картадағы аймақ талдауы • AI көмекші',
      'oldPointHeader': 'Ескі нүктені дамыту',
      'businessSection': '1. Бизнес саласы',
      'businessSectionSubtitle': 'Бір немесе бірнеше саланы таңдаңыз',
      'problemSection': '2. Негізгі мәселе',
      'problemSectionSubtitle': 'Ең көбі екі нұсқа таңдауға болады',
      'addressSection': '3. Мекенжай',
      'addressSectionSubtitle': 'Нүктенің мекенжайын енгізіңіз',
      'addressHint': 'Қала, көше немесе мекенжай',
      'otherSector': 'Басқа сала...',
      'otherBusiness': 'Басқа бизнес...',
      'otherProblem': 'Басқа мәселе...',
      'close': 'Жабу',
      'auditStart': 'АУДИТТІ БАСТАУ →',
      'auditLoading': 'Аудит дайындалуда...',
      'freeAuditNote':
          'Тегін нұсқа бастапқы есеп пен негізгі аймақ көрсеткіштерін қамтиды.',
      'auditFailed': 'Аудит орындалмады',
      'reportTitle': 'Бастапқы есеп',
      'auditReady': 'Аудит дайын',
      'score': 'Өту балы',
      'traffic': 'Жаяу жүргінші ағыны',
      'competitors': 'Бәсекелестер',
      'parking': 'Тұрақ',
      'stops': 'Аялдама',
      'reviews': 'Пікір',
      'trafficUnavailable': 'Дерек жоқ',
      'hoursAvailable': 'Кесте бар',
      'reportDescription':
          'Толық көру үшін нәтижені картадан ашыңыз. Бәсекелестерді, нүктелерді және өту балын салыстырыңыз.',
      'viewMap': 'КАРТАДАН КӨРУ',
      'fullReport': 'Толық есепті ашу',
      'paidUpgrade':
          'Ақылы нұсқа бәсекелестер картасын, толық есеп пен ұсыныстарды ашады.',
      'assistantTitle': 'AI көмекші',
      'assistantSubtitle': 'Жаңа нүкте таңдау',
      'chatHint': 'Хабарлама жазыңыз...',
      'autocompleteHint': 'Алғашқы 3 әріпті жазыңыз...',
      'assistantWelcome':
          'Сәлеметсіз бе! Бизнесіңізге мінсіз орын табуға көмектесемін. Сізде дайын нысан бар ма, әлде ең жақсы ауданды нөлден таңдап берейін бе?',
      'startNew': 'Нөлден іздеу',
      'ownAddress': 'Өз мекенжайым бар',
      'chooseBusiness': 'Жақсы. Қай бизнес саласына аймақ іздейсіз?',
      'writeAddress':
          'Мекенжайды жазыңыз. Содан кейін картадан айналаны және бәсекелестерді көрсетемін.',
      'writeArea': 'Енді ізделетін қала немесе аумақты жазыңыз.',
      'writeCustomBusiness': 'Бизнес саласын жазыңыз.',
      'writeAddressOrCity': 'Мекенжайды немесе қаланы жазыңыз.',
      'selectBusiness': 'Бұл нүкте үшін бизнес саласын таңдаңыз.',
      'analysisReady':
          'Нақты 2GIS талдауы дайын. Аймақтарды картадан көріп, бәсекелестерді салыстырыңыз.',
      'mapZones': 'АЙМАҚТАРДЫ КАРТАДАН КӨРУ',
      'analysisFailed': '2GIS талдауы орындалмады',
      'business_cafe': 'Кафе',
      'business_restaurant': 'Мейрамхана',
      'business_retail': 'Өнімдер / Бөлшек сауда',
      'business_beauty': 'Сұлулық',
      'business_health': 'Медицина',
      'business_auto': 'Автосервис',
      'business_hotel_guesthouse': 'Қонақ үй / Қонақхана',
      'business_education': 'Білім',
      'problem_traffic': 'Жаяу жүргінші ағыны азайды',
      'problem_competitors': 'Бәсекелестер пайда болды',
      'problem_ticket': 'Орташа чекті көтергім келеді',
      'problem_customers': 'Клиент ағыны аз',
      'problem_visibility': 'Көріну деңгейі төмен',
      'free': 'Тегін',
    },
  };

  static String t(String locale, String key) {
    const extra = {
      'business_pharmacy': {
        'az': 'Aptek',
        'en': 'Pharmacy',
        'ru': 'Аптека',
        'kk': 'Дәріхана',
      },
      'business_fitness': {
        'az': 'Fitnes',
        'en': 'Fitness',
        'ru': 'Фитнес',
        'kk': 'Фитнес',
      },
      'business_zoo': {
        'az': 'Zoopark / Baytarlıq',
        'en': 'Pet & veterinary',
        'ru': 'Зоо и ветклиника',
        'kk': 'Зоодүкен / Ветеринария',
      },
      'business_lab': {
        'az': 'Tibbi laboratoriya',
        'en': 'Medical laboratory',
        'ru': 'Мед. лаборатория',
        'kk': 'Медициналық зертхана',
      },
      'business_dentistry': {
        'az': 'Stomatologiya',
        'en': 'Dentistry',
        'ru': 'Стоматология',
        'kk': 'Стоматология',
      },
      'business_pickup': {
        'az': 'Çatdırılma məntəqəsi',
        'en': 'Pickup point',
        'ru': 'Пункт выдачи',
        'kk': 'Тапсырыс беру пункті',
      },
      'business_electronics': {
        'az': 'Elektronika mağazası',
        'en': 'Electronics store',
        'ru': 'Магазин электроники',
        'kk': 'Электроника дүкені',
      },
      'business_repair': {
        'az': 'Təmir / Emalatxana',
        'en': 'Repair / Workshop',
        'ru': 'Ремонт / Мастерская',
        'kk': 'Жөндеу / Шеберхана',
      },
      'business_flowers': {
        'az': 'Gül / Suvenir',
        'en': 'Flowers / Souvenirs',
        'ru': 'Цветы / Сувениры',
        'kk': 'Гүл / Кәдесый',
      },
      'business_telecom': {
        'az': 'Rabitə / Optika',
        'en': 'Telecom / Optics',
        'ru': 'Салон связи / Оптика',
        'kk': 'Байланыс / Оптика',
      },
    };
    return values[locale]?[key] ??
        values['az']![key] ??
        extra[key]?[locale] ??
        extra[key]?['az'] ??
        key;
  }
}
