#!/bin/bash
# Quick Start Guide for AI Response Testing
# Run this to see the complete test flow

echo "🚀 AI Business Agent - Quick Start Guide"
echo "========================================"
echo ""
echo "📋 SETUP INSTRUCTIONS"
echo ""
echo "1️⃣ TERMINAL 1 - Start Backend"
echo "   cd backend/"
echo "   npm run dev"
echo ""
echo "   Expected: ✅ MongoDB connected, Server running on port 5000"
echo ""
echo "2️⃣ TERMINAL 2 - Run Tests"
echo "   chmod +x test_api.sh"
echo "   ./test_api.sh"
echo ""
echo "   Expected: All tests pass, AI response received from Gemini"
echo ""
echo "========================================"
echo ""
echo "✨ CHANGES MADE:"
echo "   ✅ Gemini API key configured in .env"
echo "   ✅ /api/chat endpoint now calls Gemini API"
echo "   ✅ Automated test script created"
echo "   ✅ Complete documentation provided"
echo ""
echo "========================================"
echo ""
echo "📚 DOCUMENTATION:"
echo "   • AI_RESPONSE_TESTING.md - Complete testing guide"
echo "   • CHANGES_SUMMARY.md - Technical changes"
echo "   • AI_IMPLEMENTATION_STATUS.md - Status & verification"
echo "   • test_api.sh - Automated tests"
echo ""
echo "========================================"
echo ""
echo "🎯 MANUAL TEST COMMANDS:"
echo ""
echo "Create test user:"
echo "  curl -X POST http://localhost:5000/auth/signup \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"name\":\"Test\",\"email\":\"test@example.com\",\"password\":\"pass123\"}'"
echo ""
echo "Login:"
echo "  curl -X POST http://localhost:5000/auth/login \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"email\":\"test@example.com\",\"password\":\"pass123\"}'"
echo ""
echo "Test AI (replace TOKEN):"
echo "  curl -X POST http://localhost:5000/api/chat \\"
echo "    -H 'Authorization: Bearer TOKEN' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"prompt\":\"Tell me about coffee business\"}'"
echo ""
echo "========================================"
echo "🎉 AI Response is now working!"
echo "========================================"
